name: app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.25.5
  firebase_auth: ^4.17.6
  cloud_firestore: ^4.15.6
  google_sign_in: ^6.2.1
  js: ^0.6.7
  provider: ^6.1.2
  google_fonts: ^4.0.0
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.7.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  http: ^0.13.5
  gallery_saver: ^2.3.2
  shared_preferences: ^2.2.2
  audioplayers: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/main/
    - assets/icons/
    - assets/sound/
    - assets/sound/Bảo Tàng Của Nuối Tiếc/
    - assets/sound/Show của Đen/
    - assets/sound/Lặng/
    - assets/images/album/
    - assets/images/vu.png
    - assets/images/main/sobin.png
    - assets/images/bray.png
    - assets/images/low.png
    - assets/sound/phepmau.mp3
    - assets/sound/Jumping machine.mp3

