// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSaIQQgYypX63QDnifROmjcRSRLu3i2vs',
    appId: '1:157680094456:web:eafa392591389e4b8e3f0d',
    messagingSenderId: '157680094456',
    projectId: 'app-finish',
    authDomain: 'app-finish.firebaseapp.com',
    storageBucket: 'app-finish.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7Yp5731SJprpb-oD5EoVUR0F5XJmdv9k',
    appId: '1:157680094456:android:51a89b390b3c52428e3f0d',
    messagingSenderId: '157680094456',
    projectId: 'app-finish',
    storageBucket: 'app-finish.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSaIQQgYypX63QDnifROmjcRSRLu3i2vs',
    appId: '1:157680094456:web:87ec7e6bddbf92ac8e3f0d',
    messagingSenderId: '157680094456',
    projectId: 'app-finish',
    authDomain: 'app-finish.firebaseapp.com',
    storageBucket: 'app-finish.firebasestorage.app',
  );
}
